name: remote ssh command
on:
  push:
    paths-ignore:
      - 'docs/**'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Generate files
      run: |
        cd src
        pip install -r requirements.txt
        python app.py
        cd ..
    - name: Setup git config
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "<>"
    - name: Commit changes
      run: |
        git status
        git add docs/*
        git commit -m "generate files for pages"
    - name: Push changes
      run: |
        git push
