name: remote ssh command
on: [ push ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: build and deploy container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.MACHINE_IP }}
          username: ${{ secrets.MACHINE_USER }}
          password: ${{ secrets.MACHINE_PASSWORD }}
          port: ${{ secrets.MACHINE_PORT }}
          script: |
            cd /root/fuel_consumption
            git pull
            cd src
            docker build -t fuel_consumption .
            docker stop fuel_consumption && docker rm fuel_consumption
            docker run --name fuel_consumption --always -d -p 127.0.0.1:5001:5000 fuel_consumption
